<div data-mage-init="{&quot;accordion&quot;:{&quot;openedState&quot;: &quot;active&quot;, &quot;collapsible&quot;: true, &quot;active&quot;: false, &quot;multipleCollapsible&quot;: &quot;true&quot;}}">

    <div data-role="collapsible">
        <div class="footer-title-mobile" data-role="trigger"><?php echo __('Uk') ?></div>
    </div>
    <div data-role="content">
        <ul>
            <?php foreach ($block->geturluk() as $url) : ?>
                <?php $urlcustom = strtoupper(substr($url, (strlen($url) - 2), strlen($url))) ?>
                <li> <a href="<?php echo $url ?>"><?php echo __($urlcustom) ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<script>
    require([
        'jquery',
        'accordion'
    ], function($) {
        $("#element").accordion();
    });
</script>